### ISSUE TITLE
Add ability to not allow tracking for logged in users and certain IPs

### ISSUE THREAD

**Issue by zizther** [doublesecretagency/craft-viewcount#1]
It would be a nice feature to be able to disable logged in users as one option.
Another option which would be good is to not record an event from certain IPs

**Comment by lindseydiloreto** [comment]
Depending on [how](https://www.doublesecretagency.com/plugins/view-count/docs/how-to-increment-the-counter) you are registering the view, you can simply wrap that in a conditional tag...

```twig
{% if not currentUser %}
    {% do craft.viewCount.increment(elementId) %}
{% endif %}
```

The conditional could be as complex as you want it to be.
