### ISSUE TITLE
View Count for specified time periods

### ISSUE THREAD

**Issue by AndrewMac** [doublesecretagency/craft-viewcount#11]
Hello there

We really want to show lists of most-viewed entries for the last 24 hours, the last week, the last month, and the last year.

I've looked through the View Count documentation, but that doesn't seem to be possible; is that right? It seems that View Count only offers a sort function that operates on a normal element query, so unless it also adds something like a "dateViewed" parameter to Craft's element query we can't actually do that, can we? 

Or can we? Does View Count add an element query parameter? Or is there some other way of doing thais?

Hope I explained that well enough!

Cheers
Andrew Macpherson

**Comment by lindseydiloreto** [comment]
Hi Andrew,

The answer to this is both yes and no...

**No,** the default out-of-the-box tracking doesn't provide that much information. The tracking is condensed into a single value, which represents the cumulative number of views.

**Yes,** you can enable the "Complete View Log" to get a detailed record of each individual view. On the plugin's Settings page, you can check the box to log views on a more granular level...

<img width="314" alt="settings@2x" src="https://user-images.githubusercontent.com/5309692/114462043-5eeeb000-9b97-11eb-819d-377d627aead4.png">

All of the resulting data will be stored in the `viewcount_viewlog` table. You can access it a bit more easily using `ViewLog` records...

```php
doublesecretagency\viewcount\records\ViewLog
```

This enables a parallel track of viewing data. Your database will grow quickly, but all the information you could possibly need is right there.

Hope that helps! 🙂

**Comment by lindseydiloreto** [comment]
Whoops, I almost forgot the most important part... **you will need to use PHP to access this data**.

It's all covered in greater detail here...

 - https://plugins.doublesecretagency.com/view-count/detailed-view-log/
