### ISSUE TITLE
FR: Decrement view counts

### ISSUE THREAD

**Issue by codyjames** [doublesecretagency/craft-viewcount#15]
Here's the thing: you built a great plugin with a singular purpose but then you made it work so well for a whole lot of purposes. The purpose I'm using it for is to indicate how many folks have added an item to their shopping cart. However, I'd love to be able to both increment _and_ decrement that number. Any chance that could be added to the functionality here?

**Comment by lindseydiloreto** [comment]
That's... fascinating. I definitely intended for it to be flexible, yet somehow never thought of decrementing values.

I'm not quite ready to add a `decrement` function at this moment. This feature request fits very nicely with some long-term plans that we have for View Count. I'll leave this FR open until it one day gets added.

In the meantime, you could probably fork the plugin and add a `decrement` method of your own. Copy as much logic as you can from the [`increment` method](https://github.com/doublesecretagency/craft-viewcount/blob/94e11a9b02410f11cb0aede2efa28ae00323dcfc/src/services/View.php#L40), and just "invert the polarity", so to speak.

Hope that helps! Great suggestion, it'll definitely be added eventually. 👍

**Comment by codyjames** [comment]
Sounds good to me! Thanks, @lindseydiloreto!

**Comment by lindseydiloreto** [comment]
Good news! It's now possible to [decrement a counter](https://plugins.doublesecretagency.com/view-count/how-to-decrement-the-counter/) in **v1.2.0**.
