### ISSUE TITLE
Conflict with View class when using 'craft\web\view'

### ISSUE THREAD

**Issue by justinholtweb** [doublesecretagency/craft-viewcount#21]
Attempting to shoehorn this into an existing module that uses `use craft\web\View` and running into namespace/class collisions with the `View` class that `use doublesecretagency\viewcount\services\View` is attempting to establish. 

`Cannot use doublesecretagency\viewcount\services\View as View because the name is already in use`

- Craft CMS Pro 3.7.38
- View Count 1.0.6 (still on trial since I am still working locally)

**Comment by lindseydiloreto** [comment]
Since it's a custom module, you can probably just `use ... as ...` for either (or both) of them.

```php
use craft\web\View as CraftView
use doublesecretagency\viewcount\services\View as PluginView
```

That should prevent any conflicts in your module.

Let me know if I misunderstood something. Feel free to DM me for help troubleshooting.

**Comment by justinholtweb** [comment]
That worked! Thanks Lindsey.
