### ISSUE TITLE
FR: Methods for manipulating and resetting counts

### ISSUE THREAD

**Issue by JeanLucEsser** [doublesecretagency/craft-viewcount#23]
This is somehow related to both opened FR #2 and #15.

Would be nice to have a collection of methods allowing us to:
- decrement the value
- reset the value to 0
- reset the value to an arbitrary number
- ...

Being able to do that would allow some new scenarios, mine being as follows:

- have one count for the current month (and show it as a column in the element index)
  - resetting the counter to 0 at the start of each month
- have one count for last month
  - resetting the counter to the count of the just ended month
- have one count for the year
  - resetting every year

As discussed with @lindseydiloreto on discord, looks like I can do it by writing a module and querying the DB directly. I will probably try to do that for now, but still, I think those methods would greatly benefit the plugin. It stays in line with the "do one thing and do it right" mantra, which is counting, just with some added power.

Maybe even via an API.
What you think?

**Comment by lindseydiloreto** [comment]
Brilliant, thanks for collecting these notes @JeanLucEsser! You've neatly summarized what's "missing". 🙏 

I intend to give the View Count plugin a significant overhaul at some point. And when that day comes, I will be sure to include _all_ of these feature requests. This particular Github thread will be very useful, thank you.

Unfortunately, I do not have a planned timeline. There are several other higher priorities that already have my attention in the short term, and I don't know when the next window of opportunity will be for View Count.

I'll keep this thread open until I eventually get around to tackling it. Thanks again!

**Comment by lindseydiloreto** [comment]
Great news! As of **v1.2.0**, it's now possible to...
- [decrement the value](https://plugins.doublesecretagency.com/view-count/how-to-decrement-the-counter/)
- [reset the value to 0](https://plugins.doublesecretagency.com/view-count/setting-or-resetting-a-counter/)
- [reset the value to an arbitrary number](https://plugins.doublesecretagency.com/view-count/setting-or-resetting-a-counter/)

Hope that helps, thanks again for compiling that list of related features! 👍
