### ISSUE TITLE
allow anonymous on controller

### ISSUE THREAD

**Issue by xhuang9** [doublesecretagency/craft-viewcount#3]
I am trying to increment view by Ajax when user interact the page.

Can you add line:
```protected $allowAnonymous = true;```
in src/controllers/IncrementController.php

Thanks very much. Great plugin.

**Comment by lindseydiloreto** [comment]
Good catch, I've added this in **v1.0.1**. Thanks for the heads up!

Glad you're enjoying the plugin. 🙂
