### ISSUE TITLE
Feed Me Support

### ISSUE THREAD

**Issue by peet86** [doublesecretagency/craft-viewcount#4]
Hi, 
I'm trying to import articles from a legacy system into a new craftcms site with the help of the Feed Me plugin but it seems like the viewcount field doesn't support it.. 
In the Feed Me logs I see: 

"Trying to get property 'id' of non-object - TotalViews.php: 111."

Do you plan to support Feed Me? 

Thanks!

**Comment by lindseydiloreto** [comment]
Hi, sorry for the late response.

I believe that Feed Me support would have to be provided on the Feed Me side of things...

https://docs.craftcms.com/feed-me/v4/content-mapping/field-types.html#third-party

You may want to open an issue on the Feed Me repo.
