### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by thefubon** [doublesecretagency/craft-viewcount#5]
Please tell me how to set the counter correctly. I get an error after adding the code

```twig
{% do craft.viewCount.increment(elementId) %}
```

----

>Internal Server Error
>server error

**Comment by lindseydiloreto** [comment]
That is the correct way to [increment the counter](https://www.doublesecretagency.com/plugins/view-count/docs/how-to-increment-the-counter).

What kind of error are you getting? Can you put the site into `devMode` to get a detailed stack trace?

**Comment by lindseydiloreto** [comment]
Haven't heard back, and I can't see any reason why this code would produce an error.
