### ISSUE TITLE
Filter viewcount on a period of time

### ISSUE THREAD

**Issue by migmake** [doublesecretagency/craft-viewcount#7]
I would like to display my most viewed elements on the last X days / and on any period of time in the past...

Is it possible ?

The problem I want to solve is that the sorting of most viewed elements is not fair without the same period of time taken into account : the oldest elements have a great advantage on the last elements added into my library.

**Comment by lindseydiloreto** [comment]
Hi @migswd, sorry for the late response.

This can be done using the detailed view log...

https://www.doublesecretagency.com/plugins/view-count/docs/detailed-view-log

Be aware, some level of plugin development knowledge will be required to get the data you need. Also, the detailed view log will lead to a notably larger database. I'd recommend adding a cron job to truncate that table on a regular basis.

Hope that helps!
