### ISSUE TITLE
View counts are zero, despite data being written to db

### ISSUE THREAD

**Issue by howells** [doublesecretagency/craft-viewcount#8]
Hi - 

I'm sure I've screwed up somewhere but I can't seem to get View Count to work. I'm calling increment via JS and the relevant info seems to be written to the database: 

<img width="639" alt="Screenshot 2020-02-22 at 21 34 07" src="https://user-images.githubusercontent.com/145849/75099571-1521bf80-55bb-11ea-93e2-719379e28ed4.png">

Yet nothing is returned in the CP:

<img width="373" alt="Screenshot 2020-02-22 at 21 34 44" src="https://user-images.githubusercontent.com/145849/75099583-2d91da00-55bb-11ea-97ae-b50662309030.png">

nor are any views returns in a simply GraphQL query.

I'm not using any keys here.

Any ideas where I'm going wrong?

Dan.

**Comment by lindseydiloreto** [comment]
Hi Dan,

That's strange, it definitely looks like it _should_ be working. Can you share the Twig code you're using to log views?

One thing that's catching my eye... is the `viewKey` value being written to the database as `NULL`, or as an empty string? There is actually a difference.

**Comment by howells** [comment]
I’ve realised I might be sending and empty string as a key as part of my request (via JavaScript not twig) so I’ll check that in the morning. Thanks for the reply.

**Comment by lindseydiloreto** [comment]
Sounds great! Let me know if it turns out to be something else.

**Comment by howells** [comment]
Yeah that was the issue - all working fine now, thanks
