### ISSUE TITLE
PHP Error 'Trying to get property 'query' of non-object' on Craft 3.5.15.1

### ISSUE THREAD

**Issue by frontedbe** [doublesecretagency/craft-viewcount#9]
Hi, 

When updating to the latest Craft CMS 3.5.15.1, I get a 'Trying to get property 'query' of non-object' error in the CMS as on the front-end where a ViewCount field is used.

Any ideas what could be the issue? Thanks!

[Screenshot](https://share.getcloudapp.com/6quPpB8D)

**Comment by lindseydiloreto** [comment]
That's interesting. How were you updating (via command line or via the control panel)?

At a glance, that error doesn't make much sense. My gut is telling me that it might be a borked install. Try nuking your `vendor` folder and re-installing it.

```
rm -rf vendor/
rm composer.lock
composer clear-cache
composer update
```

**Comment by frontedbe** [comment]
Hi Lindsey,

Sorry for the late reply, I just tried what you did and all worked out :) thanks!

**Comment by lindseydiloreto** [comment]
Ok great, thanks for reporting back! 👍
